In [1]:
import torch

torch.__version__

'2.2.1+cu121'

# Tensors

## Creating tensors

In [2]:
# creating a scalar
scalar = torch.tensor(8, dtype=torch.float)
print("sacalar", scalar)
print("n dims", scalar.ndim)
# retrieving the value within the tensor
# only works with one-element tensors
print("item within tensor", scalar.item())

sacalar tensor(8.)
n dims 0
item within tensor 8.0


In [3]:
# creating a vector
vector = torch.tensor([7, 8, 9], dtype=torch.float)
print("vector", vector)
print("n dims", vector.ndim)
print("shape", vector.shape)

vector tensor([7., 8., 9.])
n dims 1
shape torch.Size([3])


In [4]:
# matrix
M = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float)
print("matrix", M)
print("n dim", M.ndim)
print("shape", M.shape)

matrix tensor([[1., 2., 3.],
        [4., 5., 6.]])
n dim 2
shape torch.Size([2, 3])


In [5]:
# tensor
T = torch.tensor([[[2, 3], [3, 4], [4, 5], [5, 6]]], dtype=torch.float)
print("tensor", T)
print("n dim", T.ndim)
print("shape", T.shape)

tensor tensor([[[2., 3.],
         [3., 4.],
         [4., 5.],
         [5., 6.]]])
n dim 3
shape torch.Size([1, 4, 2])


## Random tensors

In [6]:
random_tensor = torch.rand(size=(6, 6, 2), dtype=torch.float)
print("random tensor", random_tensor)
print("n dims", random_tensor.ndim)
print("shape", random_tensor.shape)

random tensor tensor([[[0.4307, 0.2389],
         [0.5956, 0.0937],
         [0.1541, 0.5429],
         [0.9448, 0.5986],
         [0.6958, 0.9794],
         [0.3824, 0.6893]],

        [[0.3098, 0.0373],
         [0.4739, 0.3444],
         [0.9414, 0.5594],
         [0.7223, 0.2942],
         [0.8300, 0.7810],
         [0.0680, 0.2884]],

        [[0.6441, 0.3882],
         [0.0280, 0.7789],
         [0.2986, 0.6317],
         [0.2831, 0.1002],
         [0.1677, 0.1790],
         [0.3273, 0.5293]],

        [[0.1291, 0.2323],
         [0.1903, 0.8331],
         [0.9530, 0.7669],
         [0.2085, 0.2488],
         [0.5345, 0.1736],
         [0.4895, 0.2884]],

        [[0.3405, 0.2868],
         [0.2485, 0.3532],
         [0.3673, 0.4042],
         [0.5670, 0.9519],
         [0.4081, 0.4748],
         [0.4492, 0.9510]],

        [[0.3593, 0.1143],
         [0.7582, 0.3283],
         [0.9174, 0.8725],
         [0.7400, 0.9519],
         [0.8243, 0.1497],
         [0.1073, 0.7014]]])
n 

## Zeros and Ones

In [7]:
zeros = torch.zeros(size=(2, 8))
print("zeros", zeros)
print("shape", zeros.shape)

zeros tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
shape torch.Size([2, 8])


In [8]:
ones = torch.ones(size=(2, 8))
print("ones", ones)
print("shape", ones.shape)

ones tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
shape torch.Size([2, 8])


## Ranges

In [9]:
arange = torch.arange(0, 10, 1)
print("arange", arange)
# create a tensor with the same shape like another one
zeros_like = torch.zeros_like(arange)
print("zeros like", zeros_like)

arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
zeros like tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## Useful information

In [10]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")  # will default to CPU

tensor([[3.9503e-01, 9.3234e-01, 9.4042e-01, 5.7651e-01],
        [2.8262e-01, 4.9449e-01, 7.7838e-02, 7.9192e-01],
        [7.0347e-03, 5.6980e-01, 3.1739e-04, 6.0190e-01]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Matrix Multiplication

In [36]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([[1, 2, 3], [6, 9, 3]])
print("tensor", tensor, sep="\n")
print("n dims", tensor.ndim)
print("shape", tensor.shape)

# element wise addition
print("element wise addition + 10", tensor + 10, sep="\n")

# element wise multiplication
print("element wise multiplication * 1.2", tensor * 1.2, sep="\n")
print("element wise multiplication * tensor", tensor * tensor, sep="\n")

# matrix multiplication
print("matrix multiplication", torch.matmul(tensor, tensor.T), sep="\n")

tensor
tensor([[1, 2, 3],
        [6, 9, 3]])
n dims 2
shape torch.Size([2, 3])
element wise addition + 10
tensor([[11, 12, 13],
        [16, 19, 13]])
element wise multiplication * 1.2
tensor([[ 1.2000,  2.4000,  3.6000],
        [ 7.2000, 10.8000,  3.6000]])
element wise multiplication * tensor
tensor([[ 1,  4,  9],
        [36, 81,  9]])
matrix multiplication
tensor([[ 14,  33],
        [ 33, 126]])


In [41]:
# Linear layer example
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)
print("n dims tensor A:", tensor_A.ndim)
# This uses matrix multiplication
linear = torch.nn.Linear(
    in_features=2,
    out_features=7,  # in_features = matches inner dimension of input
)  # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

n dims tensor A: 2
Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.0554,  1.0336,  0.6755,  0.5908, -0.7443,  1.0595,  0.3882],
        [ 4.3104,  2.0014,  0.6511,  0.7328, -0.5351,  2.5535,  1.6245],
        [ 6.5654,  2.9692,  0.6266,  0.8749, -0.3259,  4.0474,  2.8609]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 7])


## Positional min/max

In [42]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Reshaping, stacking, squeezing and unsqueezing

In [3]:
# Create a tensor
import torch

x = torch.arange(1.0, 8.0)
print("tensor: ", x)
print("shape: ", x.shape)

tensor:  tensor([1., 2., 3., 4., 5., 6., 7.])
shape:  torch.Size([7])


In [5]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
print("tensor with extra dim: ", x_reshaped)
print("shape: ", x_reshaped.shape)

tensor with extra dim:  tensor([[1., 2., 3., 4., 5., 6., 7.]])
shape:  torch.Size([1, 7])


In [7]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 7)
print("tensor z: ", z)
print("shape: ", z.shape)

# Changing z changes x
z[:, 0] = 5
print("tensor z: ", z)
print("tensor x: ", x)

tensor z:  tensor([[1., 2., 3., 4., 5., 6., 7.]])
shape:  torch.Size([1, 7])
tensor z:  tensor([[5., 2., 3., 4., 5., 6., 7.]])
tensor x:  tensor([5., 2., 3., 4., 5., 6., 7.])


In [8]:
# Stack tensors on top of each other
x_stacked = torch.stack(
    [x, x, x, x], dim=0
)  # try changing dim to dim=1 and see what happens
print("stacked tensor: ", x_stacked)
print("shape: ", x_stacked.shape)

stacked tensor:  tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])
shape:  torch.Size([4, 7])


In [11]:
# Remove extra dimension from x_reshaped
print(f"previous tensor: {x_reshaped}")
print(f"shape: {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"squeezed tensor: {x_squeezed}")
print(f"shape: {x_squeezed.shape}")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
shape: torch.Size([1, 7])
squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
shape: torch.Size([7])


In [14]:
print(f"previous tensor: {x_squeezed}")
print(f"shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"unsqueezed tensor: {x_unsqueezed}")
print(f"shape: {x_unsqueezed.shape}")

previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
shape: torch.Size([7])
unsqueezed tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
shape: torch.Size([1, 7])


In [16]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 225, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1)  # shifts axis 0->1, 1->2, 2->0

print(f"previous shape: {x_original.shape}")
print(f"new shape: {x_permuted.shape}")

previous shape: torch.Size([224, 225, 3])
new shape: torch.Size([3, 224, 225])


## PyTorch tensors & NumPy

In [17]:
# NumPy array to tensor
import numpy as np
import torch

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

print("np: ", array)
print("torch: ", tensor)

np:  [1. 2. 3. 4. 5. 6. 7.]
torch:  tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [18]:
# Tensor to NumPy array
tensor = torch.ones(7)  # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy()  # will be dtype=float32 unless changed
print("np: ", numpy_tensor)
print("torch: ", tensor)

np:  [1. 1. 1. 1. 1. 1. 1.]
torch:  tensor([1., 1., 1., 1., 1., 1., 1.])


## Reproducibility

In [29]:
import torch

# # Set the random seed
RANDOM_SEED = 42  # try changing this to different values and see what happens to the numbers below
torch.manual_seed(RANDOM_SEED)
A = torch.rand((3, 3, 3))

torch.manual_seed(RANDOM_SEED)
B = torch.rand((3, 3, 3))

print("are they equal?:")
A == B

are they equal?:


tensor([[[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True],
         [True, True, True]]])

# Exercises

In [1]:
import torch

torch.manual_seed(1)

In [2]:
# 1. random tensor with shape (7,7)

X = torch.rand((7, 7))
X, X.shape

(tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999, 0.3971],
         [0.7544, 0.5695, 0.4388, 0.6387, 0.5247, 0.6826, 0.3051],
         [0.4635, 0.4550, 0.5725, 0.4980, 0.9371, 0.6556, 0.3138],
         [0.1980, 0.4162, 0.2843, 0.3398, 0.5239, 0.7981, 0.7718],
         [0.0112, 0.8100, 0.6397, 0.9743, 0.8300, 0.0444, 0.0246],
         [0.2588, 0.9391, 0.4167, 0.7140, 0.2676, 0.9906, 0.2885],
         [0.8750, 0.5059, 0.2366, 0.7570, 0.2346, 0.6471, 0.3556]]),
 torch.Size([7, 7]))

In [3]:
# 2. perform a matrix multiplication from tensor X with another of shape (1,7)

Y = torch.rand((1, 7))
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[2.1819],
         [2.1090],
         [2.0406],
         [2.1226],
         [1.3201],
         [2.1429],
         [2.1000]]),
 torch.Size([7, 1]))

In [4]:
# 3. set seed to 0 and run previous excercises
torch.manual_seed(0)
X = torch.rand((7, 7))

Y = torch.rand((1, 7))
Z = torch.matmul(X, Y.T)

Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [5]:
# 4. GPU equivalent of random seed
torch.cuda.manual_seed(1234)

In [6]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU
# (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors

torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

A = torch.rand((2, 3)).to(device)
B = torch.rand((2, 3)).to(device)

A, B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))

In [7]:
# 6. Perform a matrix multiplication on the tensors
C = A @ B.T
C, C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [8]:
# 7. Find the maximum and minimum values
print(f"max: {torch.max(C)}")
print(f"min: {torch.min(C)}")

max: 0.5617256760597229
min: 0.3647301495075226


In [9]:
# 8. Find the index of the maximum and minimum values
print(f"idx of max: {torch.argmax(C)}")
print(f"idx of min: {torch.argmin(C)}")

idx of max: 3
idx of min: 0


In [10]:
# Make a random tensor with shape (1, 1, 1, 10)
# and then create a new tensor with all the 1 dimensions removed
# to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor
# and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)

M = torch.rand((1, 1, 1, 10))
N = M.squeeze()

print("first tensor\n", M, M.shape)
print("second tensor\n", N, N.shape)

first tensor
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
second tensor
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
